/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type PublicStatusPage struct {
	PublicDashboardGuid string `json:"PublicDashboardGuid,omitempty"`
	Name string `json:"Name,omitempty"`
	IsPublished bool `json:"IsPublished,omitempty"`
	PresetPeriodType *PresetPeriodType `json:"PresetPeriodType,omitempty"`
	CustomizationInfo *CustomizationInfo `json:"CustomizationInfo,omitempty"`
	SlaGuid string `json:"SlaGuid,omitempty"`
	SlaGuidSpecified bool `json:"SlaGuidSpecified,omitempty"`
	MonitorGuids []string `json:"MonitorGuids,omitempty"`
	MonitorGroupGuids []string `json:"MonitorGroupGuids,omitempty"`
}
