/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

// Information about a single assertion
type AssertionInfo struct {
	// Was the assertion completed?
	Completed bool `json:"Completed"`
	// Did the assertion pass?
	Passed bool `json:"Passed"`
	// Description
	Description string `json:"Description,omitempty"`
	// Discription of the exception trown if applicable
	ExceptionDescription string `json:"ExceptionDescription,omitempty"`
}
