/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type W3CNavigationTiming struct {
	// Equal to the requestStart as defined by the W3C.  It is a timestamp indicating when the browser starts requesting the resource from the webserver after the DNS lookup and TCP connection.
	RequestStart int32 `json:"RequestStart"`
	// Equal to the difference between navigationStart and responseStart as defined by the W3C.  In short, it's the time between when the first request was sent from browser to server, and when the first bytes of the following response were received by the browser.
	TimeToFirstByte int32 `json:"TimeToFirstByte"`
	// Equal to domInteractive as defined by W3C.  It is a timestamp, indicating the document readiness is set to 'interactive', to indicate that the browser has stopped parsing the page and the user can start interacting with it.  Resources such as scripts, images, stylesheets, or frames may still be loading.
	DomInteractive int32 `json:"DomInteractive"`
	// Equal to the domComplete as defined by W3C.  It is a timestamp, indicating when the main document has been parsed, the DOM has been fully loaded, and the page readiness is set to 'complete'.
	DomComplete int32 `json:"DomComplete"`
	// Equal to loadEventEnd as defined by W3C.  It is a timestamp, indicating when the load event of the current document has completed, including all dependent resources such as stylesheets and images.
	LoadEvent int32 `json:"LoadEvent"`
}
