/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type ExclusionPeriod struct {
	ExclusionPeriodId int32 `json:"ExclusionPeriodId,omitempty"`
	Description string `json:"Description,omitempty"`
	From interface{} `json:"From,omitempty"`
	Until interface{} `json:"Until,omitempty"`
	Hash string `json:"Hash,omitempty"`
}
