/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

// PresetPeriodTypeWithExclusive :
type PresetPeriodTypeWithExclusive string

// List of PresetPeriodTypeWithExclusive
const (
	LAST2_HOURS_EXCL   PresetPeriodTypeWithExclusive = "Last2HoursExcl"
	LAST6_HOURS_EXCL   PresetPeriodTypeWithExclusive = "Last6HoursExcl"
	LAST12_HOURS_EXCL  PresetPeriodTypeWithExclusive = "Last12HoursExcl"
	LAST24_HOURS_EXCL  PresetPeriodTypeWithExclusive = "Last24HoursExcl"
	LAST48_HOURS_EXCL  PresetPeriodTypeWithExclusive = "Last48HoursExcl"
	LAST7_DAYS_EXCL    PresetPeriodTypeWithExclusive = "Last7DaysExcl"
	LAST30_DAYS_EXCL   PresetPeriodTypeWithExclusive = "Last30DaysExcl"
	LAST60_DAYS_EXCL   PresetPeriodTypeWithExclusive = "Last60DaysExcl"
	LAST90_DAYS_EXCL   PresetPeriodTypeWithExclusive = "Last90DaysExcl"
	LAST365_DAYS_EXCL  PresetPeriodTypeWithExclusive = "Last365DaysExcl"
	LAST3_MONTHS_EXCL  PresetPeriodTypeWithExclusive = "Last3MonthsExcl"
	LAST6_MONTHS_EXCL  PresetPeriodTypeWithExclusive = "Last6MonthsExcl"
	LAST12_MONTHS_EXCL PresetPeriodTypeWithExclusive = "Last12MonthsExcl"
	LAST24_MONTHS_EXCL PresetPeriodTypeWithExclusive = "Last24MonthsExcl"
)
