/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type ScheduledReport struct {
	ScheduledReportGuid string `json:"ScheduledReportGuid,omitempty"`
	Hash string `json:"Hash,omitempty"`
	DashboardGuid string `json:"DashboardGuid,omitempty"`
	DashboardGuidSpecified bool `json:"DashboardGuidSpecified,omitempty"`
	FileType *ScheduledReportFileType `json:"FileType,omitempty"`
	IsActive bool `json:"IsActive,omitempty"`
	Schedule *Schedule `json:"Schedule,omitempty"`
	SelectedPeriod *PresetPeriodTypeWithExclusive `json:"SelectedPeriod,omitempty"`
	InternalNotes string `json:"InternalNotes,omitempty"`
	Notes string `json:"Notes,omitempty"`
	Recipients *Recipients `json:"Recipients,omitempty"`
}
