/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type WaterfallInfo struct {
	PageLoadMetrics *WaterfallInfoPageLoadMetrics `json:"PageLoadMetrics,omitempty"`
	W3CNavigationTiming *WaterfallInfoW3CNavigationTiming `json:"W3CNavigationTiming,omitempty"`
	// Elements in the waterfall
	Elements []PageElement `json:"Elements,omitempty"`
	// List of domain groups used in the waterfall elements
	DomainGroupNames []string `json:"DomainGroupNames,omitempty"`
}
