/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type AlertDefinition struct {
	// The unique key of this Alert Definition.
	AlertDefinitionGuid string `json:"AlertDefinitionGuid,omitempty"`
	// Hash corresponding with this alert definition.
	Hash string `json:"Hash,omitempty"`
	// Name of this Alert Definition.
	AlertName string `json:"AlertName,omitempty"`
	// Indicates whether this Alert Definition is active.
	IsActive bool `json:"IsActive,omitempty"`
}
