/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

// PresetPeriodTypeWithExclusive :
type PresetPeriodTypeWithExclusive string

// List of PresetPeriodTypeWithExclusive
const (
	CURRENT_DAY        PresetPeriodTypeWithExclusive = "CurrentDay"
	CURRENT_WEEK       PresetPeriodTypeWithExclusive = "CurrentWeek"
	CURRENT_MONTH      PresetPeriodTypeWithExclusive = "CurrentMonth"
	CURRENT_QUARTER    PresetPeriodTypeWithExclusive = "CurrentQuarter"
	CURRENT_YEAR       PresetPeriodTypeWithExclusive = "CurrentYear"
	PREVIOUS_DAY       PresetPeriodTypeWithExclusive = "PreviousDay"
	PREVIOUS_WEEK      PresetPeriodTypeWithExclusive = "PreviousWeek"
	PREVIOUS_MONTH     PresetPeriodTypeWithExclusive = "PreviousMonth"
	PREVIOUS_QUARTER   PresetPeriodTypeWithExclusive = "PreviousQuarter"
	PREVIOUS_YEAR      PresetPeriodTypeWithExclusive = "PreviousYear"
	LAST2_HOURS        PresetPeriodTypeWithExclusive = "Last2Hours"
	LAST6_HOURS        PresetPeriodTypeWithExclusive = "Last6Hours"
	LAST12_HOURS       PresetPeriodTypeWithExclusive = "Last12Hours"
	LAST24_HOURS       PresetPeriodTypeWithExclusive = "Last24Hours"
	LAST48_HOURS       PresetPeriodTypeWithExclusive = "Last48Hours"
	LAST7_DAYS         PresetPeriodTypeWithExclusive = "Last7Days"
	LAST30_DAYS        PresetPeriodTypeWithExclusive = "Last30Days"
	LAST60_DAYS        PresetPeriodTypeWithExclusive = "Last60Days"
	LAST90_DAYS        PresetPeriodTypeWithExclusive = "Last90Days"
	LAST365_DAYS       PresetPeriodTypeWithExclusive = "Last365Days"
	LAST3_MONTHS       PresetPeriodTypeWithExclusive = "Last3Months"
	LAST6_MONTHS       PresetPeriodTypeWithExclusive = "Last6Months"
	LAST12_MONTHS      PresetPeriodTypeWithExclusive = "Last12Months"
	LAST24_MONTHS      PresetPeriodTypeWithExclusive = "Last24Months"
	LAST2_HOURS_EXCL   PresetPeriodTypeWithExclusive = "Last2HoursExcl"
	LAST6_HOURS_EXCL   PresetPeriodTypeWithExclusive = "Last6HoursExcl"
	LAST12_HOURS_EXCL  PresetPeriodTypeWithExclusive = "Last12HoursExcl"
	LAST24_HOURS_EXCL  PresetPeriodTypeWithExclusive = "Last24HoursExcl"
	LAST48_HOURS_EXCL  PresetPeriodTypeWithExclusive = "Last48HoursExcl"
	LAST7_DAYS_EXCL    PresetPeriodTypeWithExclusive = "Last7DaysExcl"
	LAST30_DAYS_EXCL   PresetPeriodTypeWithExclusive = "Last30DaysExcl"
	LAST60_DAYS_EXCL   PresetPeriodTypeWithExclusive = "Last60DaysExcl"
	LAST90_DAYS_EXCL   PresetPeriodTypeWithExclusive = "Last90DaysExcl"
	LAST365_DAYS_EXCL  PresetPeriodTypeWithExclusive = "Last365DaysExcl"
	LAST3_MONTHS_EXCL  PresetPeriodTypeWithExclusive = "Last3MonthsExcl"
	LAST6_MONTHS_EXCL  PresetPeriodTypeWithExclusive = "Last6MonthsExcl"
	LAST12_MONTHS_EXCL PresetPeriodTypeWithExclusive = "Last12MonthsExcl"
	LAST24_MONTHS_EXCL PresetPeriodTypeWithExclusive = "Last24MonthsExcl"
	ALL                PresetPeriodTypeWithExclusive = "All"
)
