/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type ErrorCondition struct {
	ErrorConditionType *ErrorConditionErrorConditionType `json:"ErrorConditionType"`
	// The value of this error conditions (not used in all types)
	Value string `json:"Value,omitempty"`
	// The percentage of this error conditions (not used in all types)
	Percentage string                   `json:"Percentage,omitempty"`
	Level      *ErrorConditionLevel     `json:"Level,omitempty"`
	MatchType  *ErrorConditionMatchType `json:"MatchType,omitempty"`
	Effect     *ErrorConditionEffect    `json:"Effect,omitempty"`
}
