/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type Integration struct {
	// Guid of Integration in Alert Definition Escalation Level
	IntegrationGuid string `json:"IntegrationGuid"`
	// Name of Integration in Alert Definition Escalation Level
	Name string `json:"Name,omitempty"`
	Type_ *IntegrationType `json:"Type"`
	// Extra emailadresses for this integration (if type == email)
	ExtraEmailAddresses string `json:"ExtraEmailAddresses,omitempty"`
	// All statushubs for this integration (if type == statushub)
	StatusHubServiceList []IntegrationServiceMap `json:"StatusHubServiceList,omitempty"`
	// All integrations services.
	IntegrationServices []string `json:"IntegrationServices,omitempty"`
	Hash string `json:"Hash,omitempty"`
}
