/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

// Checkpoint
type Checkpoint struct {
	// The Id of the checkpoint
	CheckpointId int32 `json:"CheckpointId"`
	// The name of the checkpoint
	CheckpointName string `json:"CheckpointName,omitempty"`
	// The location code of the checkpoint
	Code string `json:"Code,omitempty"`
	// The IPv4 addresses of the checkpoint 
	Ipv4Addresses []string `json:"Ipv4Addresses,omitempty"`
	// The IPv6 addresses of the checkpoint
	Ipv6Addresses []Ipv6Address `json:"Ipv6Addresses,omitempty"`
	// Checkpoint is primary
	IsPrimaryCheckpoint bool `json:"IsPrimaryCheckpoint"`
	// Checkpoint supports IPv6
	SupportsIpv6 bool `json:"SupportsIpv6"`
	// Checkpoint has high availability
	HasHighAvailability bool `json:"HasHighAvailability"`
}
