/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

// RumMetric : Defines a RUM metric.
type RumMetric string

// List of RumMetric
const (
	PAGE_VIEWS         RumMetric = "PageViews"
	LOAD_TIME          RumMetric = "LoadTime"
	TIME_TO_FIRST_BYTE RumMetric = "TimeToFirstByte"
	PAGE_READY_TIME    RumMetric = "PageReadyTime"
	NETWORK_DURATION   RumMetric = "NetworkDuration"
	REDIRECT_DURATION  RumMetric = "RedirectDuration"
	DNS_DURATION       RumMetric = "DnsDuration"
	CONNECT_DURATION   RumMetric = "ConnectDuration"
	BACKEND_DURATION   RumMetric = "BackendDuration"
	SEND_DURATION      RumMetric = "SendDuration"
	RECEIVE_DURATION   RumMetric = "ReceiveDuration"
	FRONT_END_DURATION RumMetric = "FrontEndDuration"
	DOM_DURATION       RumMetric = "DomDuration"
	RENDER_DURATION    RumMetric = "RenderDuration"
	DOWNLOAD_TIME      RumMetric = "DownloadTime"
)
