/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

// BrowserType :
type BrowserType string

// List of BrowserType
const (
	IE                        BrowserType = "IE"
	FIREFOX                   BrowserType = "Firefox"
	CHROME                    BrowserType = "Chrome"
	SAFARI                    BrowserType = "Safari"
	PHANTOM_JS                BrowserType = "PhantomJS"
	PHANTOM_JS20              BrowserType = "PhantomJS20"
	CHROME_WITH_EXTRA_METRICS BrowserType = "ChromeWithExtraMetrics"
	EDGE                      BrowserType = "Edge"
)
