/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type RumMetricValues struct {
	Metric  *RumMetric `json:"Metric"`
	Median  int32      `json:"Median,omitempty"`
	Minimum int32      `json:"Minimum,omitempty"`
	Maximum int32      `json:"Maximum,omitempty"`
	Average int32      `json:"Average,omitempty"`
	Count   int32      `json:"Count,omitempty"`
}
