/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type Sla struct {
	// The unique key of this sla.
	SlaGuid string `json:"SlaGuid,omitempty"`
	// Hash corresponding with this sla.
	Hash string `json:"Hash,omitempty"`
	// The description name of this sla.
	Description string `json:"Description,omitempty"`
	UptimeErrorThreshold float64 `json:"UptimeErrorThreshold,omitempty"`
	UptimeWarningThreshold float64 `json:"UptimeWarningThreshold,omitempty"`
	LoadTimeErrorThreshold float64 `json:"LoadTimeErrorThreshold,omitempty"`
	OperatorReponseTimeThreshold int32 `json:"OperatorReponseTimeThreshold,omitempty"`
}
