/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type UserDefinedFunction struct {
	Name string `json:"Name,omitempty"`
	Type_ *UserDefinedFunctionType `json:"Type"`
	Mappings []UserDefinedFunctionMapping `json:"Mappings,omitempty"`
	Regex string `json:"Regex,omitempty"`
	// This property is not supported yet
	JwtSigningKey string `json:"JwtSigningKey,omitempty"`
	JwtAlgorithm *UserDefinedFunctionJwtAlgorithm `json:"JwtAlgorithm,omitempty"`
	HashKey string `json:"HashKey,omitempty"`
	HashAlgorithm *EngineHashAlgorithm `json:"HashAlgorithm"`
}
