/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

// OperatorAuthorizationType :
type OperatorAuthorizationType string

// List of OperatorAuthorizationType
const (
	ACCOUNT_ACCESS          OperatorAuthorizationType = "AccountAccess"
	ACCOUNT_ADMINISTRATOR   OperatorAuthorizationType = "AccountAdministrator"
	ALLOW_INFRA             OperatorAuthorizationType = "AllowInfra"
	FINANCIAL_OPERATOR      OperatorAuthorizationType = "FinancialOperator"
	TECHNICAL_CONTACT       OperatorAuthorizationType = "TechnicalContact"
	SHARE_DASHBOARDS        OperatorAuthorizationType = "ShareDashboards"
	CREATE_ALERT_DEFINITION OperatorAuthorizationType = "CreateAlertDefinition"
	CREATE_INTEGRATION      OperatorAuthorizationType = "CreateIntegration"
)
