/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

type EscalationLevel struct {
	EscalationMode *EscalationMode `json:"EscalationMode,omitempty"`
	Id int32 `json:"Id,omitempty"`
	ThresholdErrorCount int32 `json:"ThresholdErrorCount,omitempty"`
	ThresholdMinutes int32 `json:"ThresholdMinutes,omitempty"`
	IsActive bool `json:"IsActive,omitempty"`
	Message string `json:"Message,omitempty"`
	NumberOfReminders int32 `json:"NumberOfReminders,omitempty"`
	ReminderDelay int32 `json:"ReminderDelay,omitempty"`
	IncludeTraceRoute bool `json:"IncludeTraceRoute,omitempty"`
	// Hash corresponding with this escalation level.
	Hash string `json:"Hash,omitempty"`
}
