/*
 * Uptrends API v4
 *
 * This document describes Uptrends API version 4. This Swagger environment also lets you execute API methods directly.  Please note that this is not a sandbox environment: these API methods operate directly on your actual Uptrends account.  For more information, please visit https://www.uptrends.com/api.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package uptrends

// HttpEngineAttributes describes the attributes of a Multi-step Api monitor check
type HttpEngineAttributes struct {
	// The results of the steps 
	StepResults []HttpEngineStep `json:"StepResults,omitempty"`
	TimingInfo *HttpEngineAttributesTimingInfo `json:"TimingInfo,omitempty"`
	// Number of total steps
	TotalSteps int32 `json:"TotalSteps"`
	// Number of passed/succeed tests
	PassedSteps int32 `json:"PassedSteps"`
}
